image: Visual Studio 2022

version: 1.0.{build}

branches:
  only:
  - master

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release

artifacts:
  - path: src\CommonTK*\bin\Release\SAPTeam.CommonTK.*.nupkg

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: 2JgiRhKTzQyXmzR9JYLL6f9aNfxEKvr0pF0NxqQ1YY59O1Z5xQqI9kmDgFEiJe4y
  skip_symbols: true
